import apiClient from "./client";


const aiApi = {
  /**
   * Analyse the authenticated user's skills.
   *
   * If competencyId is null, the backend analyses
   * all competencies belonging to the current user.
   *
   * If competencyId is provided, the backend analyses
   * only that competency.
   */
  analyseSkills(competencyId = null) {
    const payload =
      competencyId === null
        ? {}
        : {
            competency_id: competencyId,
          };

    return apiClient.post(
      "/api/ai/skill-analysis",
      payload,
      {
        auth: true,
      }
    );
  },


  /**
   * Get learning recommendations for the authenticated user.
   *
   * Recommendations are generated by the backend from
   * the curated prototype learning catalogue.
   *
   * If competencyId is null, recommendations are generated
   * for all identified skill gaps.
   *
   * If competencyId is provided, recommendations are generated
   * only for that competency.
   */
  getRecommendations(competencyId = null) {
    const payload =
      competencyId === null
        ? {}
        : {
            competency_id: competencyId,
          };

    return apiClient.post(
      "/api/ai/recommendations",
      payload,
      {
        auth: true,
      }
    );
  },
};


export default aiApi;