# ============================================================
# AI QUIZ GENERATION SCHEMAS
# ============================================================
#
# Purpose:
#   Pydantic schemas used by the AI quiz generation pipeline.
#
# Flow:
#
#   Uploaded Document
#        ↓
#   document_service.py
#        ↓
#   Extracted Text
#        ↓
#   quiz_generation_service.py
#        ↓
#   GeneratedQuiz
#        ↓
#   API validation
#        ↓
#   Existing AssessmentCreate
#
# These schemas describe the AI-generation layer only.
# They do NOT replace the existing assessment schemas.
# ============================================================

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ============================================================
# TYPE DEFINITIONS
# ============================================================

QuizDifficulty = Literal[
    "easy",
    "medium",
    "hard",
]


# ============================================================
# QUIZ GENERATION REQUEST
# ============================================================


class QuizGenerationRequest(BaseModel):
    """
    Configuration for AI quiz generation.

    The actual document is uploaded separately through the
    multipart/form-data request.
    """

    question_count: int = Field(
        default=10,
        ge=1,
        le=20,
        description="Number of questions to generate.",
    )

    difficulty: QuizDifficulty | None = Field(
        default=None,
        description=(
            "Optional target difficulty. "
            "If omitted, Gemini may generate a balanced mix."
        ),
    )

    competency_name: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description=(
            "Optional competency/topic used to focus "
            "the generated questions."
        ),
    )

    @field_validator("competency_name")
    @classmethod
    def validate_competency_name(
        cls,
        value: str | None,
    ) -> str | None:
        """
        Normalize optional competency name.
        """

        if value is None:
            return None

        value = value.strip()

        if not value:
            return None

        return value


# ============================================================
# GENERATED QUIZ OPTION
# ============================================================


class GeneratedQuizOption(BaseModel):
    """
    One answer option generated by Gemini.
    """

    value: Literal[
        "A",
        "B",
        "C",
        "D",
    ]

    text: str = Field(
        ...,
        min_length=1,
        max_length=1000,
    )

    @field_validator("text")
    @classmethod
    def validate_text(
        cls,
        value: str,
    ) -> str:
        """
        Remove accidental surrounding whitespace.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Option text cannot be empty."
            )

        return value


# ============================================================
# GENERATED QUIZ QUESTION
# ============================================================


class GeneratedQuizQuestion(BaseModel):
    """
    One AI-generated multiple-choice question.
    """

    question: str = Field(
        ...,
        min_length=3,
        max_length=1000,
    )

    difficulty: QuizDifficulty

    competency: str = Field(
        ...,
        min_length=1,
        max_length=255,
    )

    options: list[GeneratedQuizOption] = Field(
        ...,
        min_length=4,
        max_length=4,
    )

    correct_answer: Literal[
        "A",
        "B",
        "C",
        "D",
    ]

    explanation: str = Field(
        ...,
        min_length=1,
        max_length=2000,
    )

    hint: str = Field(
        ...,
        min_length=1,
        max_length=1000,
    )

    @field_validator("question")
    @classmethod
    def validate_question(
        cls,
        value: str,
    ) -> str:
        """
        Normalize question text.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Question text cannot be empty."
            )

        return value

    @field_validator("competency")
    @classmethod
    def validate_competency(
        cls,
        value: str,
    ) -> str:
        """
        Normalize competency name.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Competency cannot be empty."
            )

        return value

    @field_validator("explanation")
    @classmethod
    def validate_explanation(
        cls,
        value: str,
    ) -> str:
        """
        Normalize explanation.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Explanation cannot be empty."
            )

        return value

    @field_validator("hint")
    @classmethod
    def validate_hint(
        cls,
        value: str,
    ) -> str:
        """
        Normalize hint.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Hint cannot be empty."
            )

        return value

    @field_validator("options")
    @classmethod
    def validate_options(
        cls,
        value: list[GeneratedQuizOption],
    ) -> list[GeneratedQuizOption]:
        """
        Ensure exactly A, B, C and D exist once each.
        """

        if len(value) != 4:
            raise ValueError(
                "Each question must contain exactly "
                "four options."
            )

        option_values = [
            option.value
            for option in value
        ]

        if len(set(option_values)) != 4:
            raise ValueError(
                "Question options must have unique values."
            )

        if set(option_values) != {
            "A",
            "B",
            "C",
            "D",
        }:
            raise ValueError(
                "Question options must contain "
                "A, B, C and D."
            )

        option_texts = [
            " ".join(
                option.text.lower().split()
            )
            for option in value
        ]

        if len(set(option_texts)) != 4:
            raise ValueError(
                "Question options must contain "
                "distinct text."
            )

        return value

    @field_validator("correct_answer")
    @classmethod
    def validate_correct_answer(
        cls,
        value: str,
    ) -> str:
        """
        Normalize the correct-answer identifier.
        """

        return value.strip().upper()


# ============================================================
# GENERATED QUIZ
# ============================================================


class GeneratedQuiz(BaseModel):
    """
    Complete AI-generated quiz.

    This is the main internal/API representation produced by
    the quiz generation service.
    """

    title: str = Field(
        default="AI Generated Assessment",
        min_length=2,
        max_length=255,
    )

    description: str = Field(
        default=(
            "Assessment generated from the supplied "
            "learning material."
        ),
        min_length=1,
        max_length=2000,
    )

    questions: list[GeneratedQuizQuestion] = Field(
        ...,
        min_length=1,
        max_length=20,
    )

    @field_validator("title")
    @classmethod
    def validate_title(
        cls,
        value: str,
    ) -> str:
        """
        Normalize quiz title.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Quiz title cannot be empty."
            )

        return value

    @field_validator("description")
    @classmethod
    def validate_description(
        cls,
        value: str,
    ) -> str:
        """
        Normalize quiz description.
        """

        value = value.strip()

        if not value:
            raise ValueError(
                "Quiz description cannot be empty."
            )

        return value

    @field_validator("questions")
    @classmethod
    def validate_questions(
        cls,
        value: list[GeneratedQuizQuestion],
    ) -> list[GeneratedQuizQuestion]:
        """
        Ensure questions are not duplicates.
        """

        if not value:
            raise ValueError(
                "Generated quiz must contain at least "
                "one question."
            )

        normalized_questions: list[str] = []

        for question in value:
            normalized = " ".join(
                question.question.lower().split()
            )

            normalized_questions.append(
                normalized
            )

        if len(normalized_questions) != len(
            set(normalized_questions)
        ):
            raise ValueError(
                "Generated quiz contains duplicate questions."
            )

        return value


# ============================================================
# GENERATION RESPONSE
# ============================================================


class QuizGenerationResponse(BaseModel):
    """
    API response returned after successful AI quiz generation.
    """

    quiz: GeneratedQuiz

    source_filename: str = Field(
        ...,
        min_length=1,
        max_length=255,
    )

    source_type: str = Field(
        ...,
        min_length=1,
        max_length=20,
    )

    question_count: int = Field(
        ...,
        ge=1,
        le=20,
    )

    ai_generated: bool = True

    source_note: str = Field(
        default=(
            "Questions were generated by Gemini from "
            "the uploaded learning material and validated "
            "by the backend."
        ),
        min_length=1,
        max_length=1000,
    )


# ============================================================
# GENERATED QUESTION → EXISTING ASSESSMENT FORMAT
# ============================================================
#
# Existing assessment system stores options as:
#
#     list[str]
#
# and correct_answer as:
#
#     str
#
# Therefore this helper converts:
#
#     [
#         {"value": "A", "text": "..."},
#         {"value": "B", "text": "..."},
#         ...
#     ]
#
# into:
#
#     ["...", "...", "...", "..."]
#
# and:
#
#     "..."
#
# without changing the existing AssessmentQuestion schema.
# ============================================================


class GeneratedAssessmentQuestionPayload(BaseModel):
    """
    Payload compatible with the existing assessment creation
    system.

    This schema is useful when the trainer approves an
    AI-generated quiz and it needs to be saved.
    """

    competency_id: int = Field(
        ...,
        gt=0,
    )

    question_text: str = Field(
        ...,
        min_length=3,
        max_length=1000,
    )

    options: list[str] = Field(
        ...,
        min_length=4,
        max_length=4,
    )

    correct_answer: str = Field(
        ...,
        min_length=1,
        max_length=255,
    )

    difficulty: str = Field(
        default="medium",
        min_length=3,
        max_length=20,
    )

    explanation: str | None = Field(
        default=None,
        max_length=2000,
    )


# ============================================================
# TRAINER PREVIEW RESPONSE
# ============================================================


class QuizPreviewResponse(BaseModel):
    """
    Lightweight response for trainer preview/edit screens.

    This does not publish or save an assessment.
    """

    quiz: GeneratedQuiz

    source_filename: str

    question_count: int

    requires_review: bool = True

    review_note: str = (
        "AI-generated questions should be reviewed by "
        "the trainer before publishing."
    )